
export const countryCityData = [
  { name: "Afghanistan", cities: ["Kabul", "Kandahar", "Herat", "Mazar-i-Sharif"] },
  { name: "Algeria", cities: ["Algiers", "Oran", "Constantine", "Annaba"] },
  { name: "Angola", cities: ["Luanda", "Huambo", "Lobito"] },
  { name: "Argentina", cities: ["Buenos Aires", "Cordoba", "Rosario"] },
  { name: "Australia", cities: ["Sydney", "Melbourne", "Brisbane", "Perth"] },
  { name: "Austria", cities: ["Vienna", "Graz", "Linz"] },
  { name: "Bahrain", cities: ["Manama", "Riffa", "Muharraq"] },
  { name: "Bangladesh", cities: ["Dhaka", "Chittagong", "Khulna"] },
  { name: "Belarus", cities: ["Minsk", "Gomel", "Mogilev"] },
  { name: "Belgium", cities: ["Brussels", "Antwerp", "Ghent"] },
  { name: "Benin", cities: ["Cotonou", "Porto-Novo", "Parakou"] },
  { name: "Bolivia", cities: ["La Paz", "Santa Cruz de la Sierra", "Cochabamba"] },
  { name: "Botswana", cities: ["Gaborone", "Francistown", "Molepolole"] },
  { name: "Brazil", cities: ["São Paulo", "Rio de Janeiro", "Brasília"] },
  { name: "Bulgaria", cities: ["Sofia", "Plovdiv", "Varna"] },
  { name: "Cambodia", cities: ["Phnom Penh", "Siem Reap", "Battambang"] },
  { name: "Cameroon", cities: ["Yaoundé", "Douala", "Garoua"] },
  { name: "Canada", cities: ["Toronto", "Montreal", "Vancouver", "Calgary"] },
  { name: "Chad", cities: ["N'Djamena", "Moundou", "Sarh"] },
  { name: "Chile", cities: ["Santiago", "Valparaíso", "Concepción"] },
  { name: "China", cities: ["Shanghai", "Beijing", "Chongqing"] },
  { name: "Colombia", cities: ["Bogotá", "Medellín", "Cali"] },
  { name: "Congo, Democratic Republic of the", cities: ["Kinshasa", "Lubumbashi", "Mbuji-Mayi"] },
  { name: "Croatia", cities: ["Zagreb", "Split", "Rijeka"] },
  { name: "Cyprus", cities: ["Nicosia", "Limassol", "Larnaca"] },
  { name: "Czech Republic", cities: ["Prague", "Brno", "Ostrava"] },
  { name: "Denmark", cities: ["Copenhagen", "Aarhus", "Odense"] },
  { name: "Ecuador", cities: ["Quito", "Guayaquil", "Cuenca"] },
  { name: "Egypt", cities: ["Cairo", "Alexandria", "Giza"] },
  { name: "Estonia", cities: ["Tallinn", "Tartu", "Narva"] },
  { name: "Ethiopia", cities: ["Addis Ababa", "Gondar", "Mek'ele"] },
  { name: "Fiji", cities: ["Suva", "Nadi", "Lautoka"] },
  { name: "Finland", cities: ["Helsinki", "Espoo", "Tampere"] },
  { name: "France", cities: ["Paris", "Marseille", "Lyon"] },
  { name: "Gabon", cities: ["Libreville", "Port-Gentil", "Franceville"] },
  { name: "Germany", cities: ["Berlin", "Hamburg", "Munich"] },
  { name: "Ghana", cities: ["Accra", "Kumasi", "Tamale"] },
  { name: "Greece", cities: ["Athens", "Thessaloniki", "Patras"] },
  { name: "Guinea", cities: ["Conakry", "Nzérékoré", "Kankan"] },
  { name: "Hungary", cities: ["Budapest", "Debrecen", "Szeged"] },
  { name: "India", cities: ["Delhi", "Mumbai", "Bangalore"] },
  { name: "Indonesia", cities: ["Jakarta", "Surabaya", "Bandung"] },
  { name: "Iran", cities: ["Tehran", "Mashhad", "Isfahan"] },
  { name: "Iraq", cities: ["Baghdad", "Basra", "Mosul"] },
  { name: "Ireland", cities: ["Dublin", "Cork", "Limerick"] },
  { name: "Israel", cities: ["Jerusalem", "Tel Aviv", "Haifa"] },
  { name: "Italy", cities: ["Rome", "Milan", "Naples"] },
  { name: "Ivory Coast", cities: ["Yamoussoukro", "Abidjan", "Bouaké"] },
  { name: "Japan", cities: ["Tokyo", "Yokohama", "Osaka"] },
  { name: "Jordan", cities: ["Amman", "Zarqa", "Irbid"] },
  { name: "Kazakhstan", cities: ["Nur-Sultan", "Almaty", "Shymkent"] },
  { name: "Kenya", cities: ["Nairobi", "Mombasa", "Kisumu"] },
  { name: "Kuwait", cities: ["Kuwait City", "Al Ahmadi", "Hawalli"] },
  { name: "Laos", cities: ["Vientiane", "Pakse", "Savannakhet"] },
  { name: "Latvia", cities: ["Riga", "Daugavpils", "Liepāja"] },
  { name: "Lebanon", cities: ["Beirut", "Tripoli", "Sidon"] },
  { name: "Libya", cities: ["Tripoli", "Benghazi", "Misrata"] },
  { name: "Lithuania", cities: ["Vilnius", "Kaunas", "Klaipėda"] },
  { name: "Luxembourg", cities: ["Luxembourg", "Esch-sur-Alzette", "Differdange"] },
  { name: "Madagascar", cities: ["Antananarivo", "Toamasina", "Antsirabe"] },
  { name: "Malaysia", cities: ["Kuala Lumpur", "George Town", "Johor Bahru"] },
  { name: "Mali", cities: ["Bamako", "Sikasso", "Mopti"] },
  { name: "Mexico", cities: ["Mexico City", "Guadalajara", "Monterrey"] },
  { name: "Mongolia", cities: ["Ulaanbaatar", "Erdenet", "Darkhan"] },
  { name: "Morocco", cities: ["Rabat", "Casablanca", "Fes"] },
  { name: "Mozambique", cities: ["Maputo", "Matola", "Beira"] },
  { name: "Myanmar", cities: ["Naypyidaw", "Yangon", "Mandalay"] },
  { name: "Namibia", cities: ["Windhoek", "Rundu", "Walvis Bay"] },
  { name: "Nepal", cities: ["Kathmandu", "Pokhara", "Lalitpur"] },
  { name: "Netherlands", cities: ["Amsterdam", "Rotterdam", "The Hague"] },
  { name: "New Zealand", cities: ["Wellington", "Auckland", "Christchurch"] },
  { name: "Niger", cities: ["Niamey", "Zinder", "Maradi"] },
  { name: "Nigeria", cities: ["Abuja", "Lagos", "Kano"] },
  { name: "Norway", cities: ["Oslo", "Bergen", "Trondheim"] },
  { name: "Oman", cities: ["Muscat", "Seeb", "Salalah"] },
  { name: "Pakistan", cities: ["Islamabad", "Karachi", "Lahore"] },
  { name: "Papua New Guinea", cities: ["Port Moresby", "Lae", "Arawa"] },
  { name: "Paraguay", cities: ["Asunción", "Ciudad del Este", "San Lorenzo"] },
  { name: "Peru", cities: ["Lima", "Arequipa", "Trujillo"] },
  { name: "Philippines", cities: ["Manila", "Quezon City", "Davao City"] },
  { name: "Poland", cities: ["Warsaw", "Kraków", "Łódź"] },
  { name: "Portugal", cities: ["Lisbon", "Porto", "Amadora"] },
  { name: "Qatar", cities: ["Doha", "Al Rayyan", "Al Wakrah"] },
  { name: "Romania", cities: ["Bucharest", "Cluj-Napoca", "Timișoara"] },
  { name: "Russia", cities: ["Moscow", "Saint Petersburg", "Novosibirsk"] },
  { name: "Saudi Arabia", cities: ["Riyadh", "Jeddah", "Mecca"] },
  { name: "Senegal", cities: ["Dakar", "Touba", "Thiès"] },
  { name: "Singapore", cities: ["Singapore"] },
  { name: "Slovakia", cities: ["Bratislava", "Košice", "Prešov"] },
  { name: "Slovenia", cities: ["Ljubljana", "Maribor", "Celje"] },
  { name: "Somalia", cities: ["Mogadishu", "Hargeisa", "Bosaso"] },
  { name: "South Africa", cities: ["Pretoria", "Cape Town", "Johannesburg"] },
  { name: "South Korea", cities: ["Seoul", "Busan", "Incheon"] },
  { name: "Spain", cities: ["Madrid", "Barcelona", "Valencia"] },
  { name: "Sri Lanka", cities: ["Colombo", "Kandy", "Galle"] },
  { name: "Sudan", cities: ["Khartoum", "Omdurman", "Port Sudan"] },
  { name: "Sweden", cities: ["Stockholm", "Gothenburg", "Malmö"] },
  { name: "Switzerland", cities: ["Bern", "Zürich", "Geneva"] },
  { name: "Syria", cities: ["Damascus", "Aleppo", "Homs"] },
  { name: "Tanzania", cities: ["Dodoma", "Dar es Salaam", "Mwanza"] },
  { name: "Thailand", cities: ["Bangkok", "Nonthaburi", "Nakhon Ratchasima"] },
  { name: "Tunisia", cities: ["Tunis", "Sfax", "Sousse"] },
  { name: "Turkey", cities: ["Ankara", "Istanbul", "İzmir"] },
  { name: "Uganda", cities: ["Kampala", "Gulu", "Lira"] },
  { name: "Ukraine", cities: ["Kyiv", "Kharkiv", "Odesa"] },
  { name: "United Arab Emirates", cities: ["Abu Dhabi", "Dubai", "Sharjah"] },
  { name: "United Kingdom", cities: ["London", "Birmingham", "Manchester"] },
  { name: "United States", cities: ["Washington, D.C.", "New York City", "Los Angeles"] },
  { name: "Uruguay", cities: ["Montevideo", "Salto", "Ciudad de la Costa"] },
  { name: "Venezuela", cities: ["Caracas", "Maracaibo", "Valencia"] },
  { name: "Vietnam", cities: ["Hanoi", "Ho Chi Minh City", "Da Nang"] },
  { name: "Yemen", cities: ["Sana'a", "Aden", "Ta'izz"] },
  { name: "Zambia", cities: ["Lusaka", "Kitwe", "Ndola"] },
  { name: "Zimbabwe", cities: ["Harare", "Bulawayo", "Chitungwiza"] }
].sort((a, b) => a.name.localeCompare(b.name));
